
language: node_js
node_js: '10'

cache:
  directories:
    - ~/.npm

env:
  global:
    - FORCE_COLOR=1

script:
  - npm run prettier
  - npm run tslint
  - npm run build
  - npm run typecheck
  - npm run cover
  - ./node_modules/.bin/nyc report --reporter json
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
